config/routes.rb
# Plugin's routes
# See: http://guides.rubyonrails.org/routing.html
resources :jp_people, path: :address
match 'address/preview/(:id)' => 'jp_people#preview', as: :jp_people_preview, via: [:post, :patch, :put]
# match 'addrsss/search' => 'jp_people#search', as: :jp_people_search, via:[:get, :post]
resources :projects do
  get 'address/add' => 'jp_people#add'
  post 'address/search_people' => 'jp_people#search_people'
  post 'address/add_people' => 'jp_people#add_people'
  resources :jp_people, path: :address
end
resources :projects_jp_people

app/controllers/jp_people_controller.rb
class JpPeopleController < ApplicationController
  # unloadable
  helper :sort
  include SortHelper
  model_object JpPerson
  before_action :set_person, only: [:show, :edit, :update, :destroy]
  before_action :set_project #, :only => [:index, :new, :create, :edit, :update] 

  def index
    @q ||= params[:q]
    sort_init 'jp_people.kana'
    sort_update %w(jp_people.name jp_people.kana)
    @people = JpPerson.search_by_project_id(@project).search(@q).order(sort_clause)
    if @people.blank?
      @people = JpPerson.search_by_project_id(@project).phone_search(@q).order(sort_clause)
    end
    if @people.blank?
      @people = JpPerson.search_by_project_id(@project).mail_search(@q).order(sort_clause)
    end
    @limit = per_page_option
    @people_count = @people.count
    @person_pages = Paginator.new @people_count, @limit, params['page']
    respond_to do |format|
      format.html
      format.js
    end
  end

  def show
  end

  def new
    @person = JpPerson.new
    @person.projects_jp_people.build(project_id: @project.id) unless @project == nil
  end

  def create
    @person = JpPerson.new(person_params)

    respond_to do |format|
      if @person.save
        format.html { redirect_to @person, 
                      notice: t(:notice_create_person, name: @person.name) }
      else
        format.html { render :new }
      end
    end
  end

  def edit
    if @project.present?
      @person.projects_jp_people.find_by(project_id: @project.id)
    end
  end

  def update
    respond_to do |format|
      if @person.update(person_params)
        format.html { redirect_to @person,
                      notice: t(:notice_update_person, name: @person.name) }
      else
        format.html { render :edit }
      end
    end
  end

  def add
    @query ||= ''
    @candidates = JpPerson.not_added(@project).search(@query).limit(8)
  end

  def add_people
    candidate_ids = params[:candidate][:id]
    candidate_ids.each do |id|
      @project.projects_jp_people.build(jp_person_id: id.to_i)
    end
    if @project.save!
      msg = '追加しました.'
    else
      msg = '追加できませんでした.'
    end
    redirect_to project_jp_people_path(@project),notice: msg 
  end

  def search_people
    @query = params[:query]
    @candidates = JpPerson.not_added(@project).search(@query).limit(8)
    respond_to do |format|
      format.js
    end
  end

  def destroy
    @person.destroy
    return_url = @project.present? ? projects_jp_people_url : jp_people_url
    respond_to do |format|
      format.html { redirect_to return_url,
                    notice: t(:notice_destroy_person, name: @person.name) }
    end
  end

  def preview
    @text = params[:jp_person][:memo]
    render :partial => 'common/preview'
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_person
    @person = JpPerson.find(params[:id])
  end

  def set_project
    project_id = params[:project_id]
    @project = Project.find(project_id)
    @parent_project = Project.find(@project.parent_id) if @project.parent_id.present?
  rescue
    return
  end

  def set_project_from_assoc
    @project = @object.projects.find(params[:project_id])
  end
  # Never trust parameters from the scary internet, only allow the white list through.
  def person_params
    params.require(:jp_person)
      .permit(:name, :kana, :is_corporate, :represent, :represent_katagaki, :memo,
              jp_addresses_attributes: [:id, :label, :zip_code, :todofuken,
                                        :address1, :address2, :building, :corporate, :_destroy],
              jp_e_mails_attributes: [:id, :label, :mail_address, :_destroy],
              jp_phone_numbers_attributes: [:id, :label, :number, :_destroy],
              projects_jp_people_attributes: [:id, :project_id, :jp_people_id, :pp_relationship, :is_project_owner]
             )
  end

end

app/helpers/jp_people_helper.rb
module JpPeopleHelper
  TODOFUKEN = JpPrefecture::Prefecture.all.map{|p| p.name}
  def todofuken_name
    TODOFUKEN << 'その他'
  end

  def render_projects_jp_people(person)
    # logger.debug person
    render partial: 'projects_jp_people/index_table', :locals => {person: person}
  end
end

app/views/jp_people/_candidates.html.erb
<% if candidates.any? %>
    <table>
      <tr>
        <td>追加</td>
        <td>名前</td>
      </tr>
      <% candidates.each do |candidate| %>
        <tr>
          <td><%= check_box_tag 'candidate[id][]', candidate.id %></td>
          <td><%= label_tag  candidate.name %> </td>
        </tr>
      <% end %>
    </table>
<% else %>
  <p class="nodata"><%= l(:label_no_data) %></p>
<% end %>

app/views/jp_people/_form_add_from_people.html.erb
<div id="dialog" title="<%= l(:new_projects_jp_person) %>">
  <% if project.jp_people.any? %>
    <fieldset class="box">
      <legend>プロジェクトに追加済みのアドレス</legend>
      <%= project.jp_people.map {|person| person.name}.join(' , ')%>
    </fieldset>
  <% end %>
    <%= text_field_tag :query,@query, id: 'query' %>
    <%= form_tag controller: :jp_people, action: :add_people do %>
      <fieldset class="box">
        <div id="candidates">
          <%= render partial: 'candidates', locals: {candidates: @candidates} %>
        </div>
      </fieldset>
      <%= submit_tag "追加" , class: 'button add' %>
      <button type="button cancel" class="button" onClick="cancel();">Cancel</button>
    <% end %>
</div>
<script>
  $('.button').button();
       $('#query').on("keyup", function(e){
         query = $(this).val();
         $.ajax({
           url: "<%=j project_address_search_people_path %>",
          type: 'POST',
          data: {
            query: query 
          }
         });
       })
     </script>

app/views/jp_people/_jp_address_fields.html.erb
<div class="field box tabular">
  <p style="float:right; margin-right:1em;">
    <%= f.link_to_remove '', class: 'ui-icon ui-icon-closethick' %>
  </p>
  <p><%= f.label :label %><%= f.text_field :label %></p>
  <p><%= f.label :zip_code %><%= f.text_field :zip_code, class: 'zip_code' %></p>
  <p><%= f.label :todofuken %><%= f.select :todofuken, todofuken_name,{}, class: 'todofuken' %></p>
  <p><%= f.label :address1 %><%= f.text_field :address1, size: 70, class: 'address1'%></p>
  <p><%= f.label :address2 %><%= f.text_field :address2, size: 70, class: 'address2' %></p>
  <p><%= f.label :building %><%= f.text_field :building, size: 50, class: 'building' %></p>
  <p><%= f.label :corporate %><%= f.text_field :corporate, size: 50, class: 'corporate' %></p>
</div>

app/views/jp_people/_jp_e_mail_fields.html.erb
<div class="field box tabular">
  <p style="float:right; margin-right:1em;">
    <%= f.link_to_remove '', class: 'ui-icon ui-icon-closethick' %>
  </p>
  <p><%= f.label :label %><%= f.text_field :label %></p>
  <p><%= f.label :mail_address %><%= f.email_field :mail_address %></p>
</div>

app/views/jp_people/_jp_phone_number_fields.html.erb
<div class="field box tabular">
  <p style="float:right; margin-right:1em;">
    <%= f.link_to_remove '', class: 'ui-icon ui-icon-closethick' %>
  </p>
  <p><%= f.label :label %><%= f.text_field :label %></p>
  <p><%= f.label :number %><%= f.telephone_field :number %></p>
</div>

app/views/jp_people/_projects_jp_person_fields.html.erb
  <%= f.hidden_field :project_id, value: @project.id  %>
  <p><%= f.label :pp_relationship %><%= f.text_field :pp_relationship %></p>
  <p><%= f.label :is_project_owner %><%= f.check_box :is_project_owner %></p>

app/views/jp_people/_table_items.html.erb
<% if @people.empty? %>
  <p class="nodata"><%= l(:label_no_data) %></p>
<% else %>
  <table class="list">
    <thead>
      <% if @project.present? %>
        <th><%= l(:field_pp_relationship) %></th>
      <% end %>
      <%= sort_header_tag 'jp_people.name', caption: l(:field_name)%>
      <%= sort_header_tag 'jp_people.kana', caption: l(:field_kana)%>
      <th><%= l(:field_number)%></th>
      <th><%= l(:field_mail_address)%></th>
    </thead>
    <% @people.each do |person| %>
      <tr>
        <% if @project.present? %>
          <td>
            <% pr = person.projects_jp_people %>
            <% if this_person = pr.find_by(project_id: @project.id) %>
              <%= content_tag :span, "●", class: :is_project_owner if this_person.is_project_owner %>

              <%= this_person.pp_relationship%>
            <% elsif this_person = pr.find_by(project_id: @parent_project.id)%>
              <%= content_tag :span, "●", class: :is_project_owner if this_person.is_project_owner %>

              <%= this_person.pp_relationship%>
            <% end %>
          </td>
          <td><%= link_to person.name, project_jp_person_path(project_id: @project.id, id: person.id) %></td>
        <% else %>
          <td><%= link_to person.name, person %></td>
        <% end %>
        <td><%= person.kana %></td>
        <td><%= person.jp_phone_numbers.first.number if person.jp_phone_numbers.first.present? %></td>
        <td><%= person.jp_e_mails.first.mail_address if person.jp_e_mails.first.present? %></td>
      </tr>
    <% end %>
  </table>
  <p class="pagination">
    <%= pagination_links_full @person_pages, @people_count %>
  </p>
<% end %> 

app/views/jp_people/add.js.erb
options = {
  width: 500, 
  height: 500, 
  modal: true,
  close: function(){
    dialog.dialog("destroy");
  }
};
$('#modal_area').html('<%= escape_javascript(render :partial => 'form_add_from_people', :locals => {:project => @project}) %>')
  .hide()
dialog = $('#dialog').dialog(options).show('blind')
function cancel(){
  dialog.dialog("close");
  $('#modal_area').html('');
}

app/views/jp_people/index.html.erb
<% content_for :header_tags do %>
  <%= stylesheet_link_tag 'jp_address', :plugin => 'redmine_jp_address' %>
<% end %>

<div class="contextual">
  <% if @project.nil? %>
    <%= link_to l(:new_person), new_jp_person_path, class: 'icon icon-add' %>
  <% else %>
    <%= link_to l(:new_person), new_project_jp_person_path, class: 'icon icon-add' %> |
    <%= link_to l(:new_projects_jp_person), project_address_add_path(@project.id), remote: true, class: 'icon icon-add'%>
  <% end %>
</div>

<h2><%= l(:people_index) %></h2>
<%= form_tag jp_people_path,method: :get, remote: true, id: 'search_bar' do %>
  <p>検索 <%= text_field_tag :q,@q, size: 40 %></p>
  <% if @project.present? %>
    <%= hidden_field_tag :project_id, @project.id%>
  <% end %>
<% end %>
<div id="index_table">
  <%= render 'table_items' %>
</div>
<% if @project.present? %>
<p>* <span class="is_project_owner">●</span>はプロジェクトオーナー</p>
<% end %>

<div id="modal_area" class="hidden"></div>
<% content_for :sidebar do %>
  <div></div>
<% end %>

<% html_title l(:people_index) %>

app/views/jp_people/index.js.erb
$('#index_table').html('<%= escape_javascript(render :partial => 'table_items', :locals => {:people => @people}) %>')

app/views/jp_people/new.html.erb
<% content_for :header_tags do %>
  <%= stylesheet_link_tag 'jp_address', :plugin => 'redmine_jp_address' %>
<% end %>
<div class="contextual">
  <%= link_to l(:cancel), jp_people_path, class: 'icon icon-cancel' %>
</div>
<h2><%= l(:new_person)%></h2>
<%= render 'form' %>
<% content_for :sidebar do %>
  <div></div>
<% end %>

<% html_title l(:new_person) %>

app/views/jp_people/search.js.erb
$('#index_table').html('<%= escape_javascript(render :partial => 'table_items', :locals => {:people => @people}) %>')

app/views/jp_people/search_people.js.erb
$('#candidates').html('<%= escape_javascript(render partial: 'candidates', locals: {candidates: @candidates}) %>')

app/views/jp_people/show.html.erb
<% content_for :header_tags do %>
  <%= stylesheet_link_tag 'jp_address', :plugin => 'redmine_jp_address' %>
<% end %>
<div class="contextual">
  <% if @project.present? %>
    <%= link_to l(:edit), edit_project_jp_person_path, class: 'icon icon-edit' %> | 
  <% else %>
    <%= link_to l(:edit), edit_jp_person_path, class: 'icon icon-edit' %> | 
  <% end %>
  <%= link_to l(:delete), @person, method: :delete,
    data: { confirm: t(:delete_confirm_message, name: @person.name) }, 
    class: 'icon icon-del' %> | 
  <%= link_to l(:back), :back  %>
</div>

<h2><%= t(:show_person, name: @person.name) %></h2>
<div class="box">
  <h3><%= l(:basic_info) %></h3>
  <p><%= @person.name %></p>
  <p><%= @person.kana %></p>
  <% if @person.is_corporate %>
    <p><%= @person.represent_katagaki %>
    <%= @person.represent %></p>
  <% end %>
</div>
<% if @person.jp_addresses.present? %>
  <div class="box">
    <h3><%= l(:address_info) %></h3>
    <% @person.jp_addresses.each do |address| %>
      <h4><%= address.label %></h4>
      <p>〒 <%= address.zip_code %></p>
      <p><%= address.todofuken %>
      <%= address.address1 %>
      <%= address.address2 %></p>
    <p><%= address.building %></p>
    <p><%= address.corporate %></p>
  <% end %>
</div>
 <% end %>
 <% if @person.jp_phone_numbers.present? %>
   <div class="box">
     <h3><%= l(:tel_info) %></h3>
     <% @person.jp_phone_numbers.each do |phone_number| %>
       <h4><%= phone_number.label %></h4>
       <p><%= phone_number.number %></p>
     <% end %>
   </div>
 <% end %>
 <% if @person.jp_e_mails.present? %>
   <div class="box">
     <h3><%= l(:email_info) %></h3>
     <% @person.jp_e_mails.each do |e_mail| %>
       <p><%= e_mail.label %><%= mail_to e_mail.mail_address %></p>
     <% end %>
   </div>
 <% end %>
 <% if @person.memo.present? %>
   <div class="box">
     <h3><%= l(:memo_info) %></h3>
     <div class="wiki">
       <%= textilizable @person.memo %>
     </div>
   </div>
 <% end %>

 <% content_for :sidebar do %>
   <h3>情報</h3>
   <h4>プロジェクトに追加</h4>
   <%= form_for(ProjectsJpPerson.new, remote: true) do |f| %>
     <%= f.hidden_field :jp_person_id, value: @person.id %>
     <p><%= f.collection_select :project_id, Project.allowed_to(User.current), :id, :name %></p>
     <p>関連 <%= f.text_field :pp_relationship %></p>
     <p>プロジェクトオーナー <%= f.check_box  :is_project_owner %></p>
     <p><%= f.submit l(:button_add) %></p>
   <% end %>
   <h4>関連するプロジェクト</h4>
   <div id="projects_jp_people_table">
     <%= render_projects_jp_people @person %>
   </div>
   <% if @project.present? %>
     <h4>このプロジェクトから削除</h4>
     <p>
       <%= link_to l(:delete), @person.projects_jp_people.find_by(project_id: @project.id ), method: :delete,
         data: {confirm: '本当に削除しますか'},
         class: 'icon icon-del'%>
     </p>
   <% end %>
 <% end %>
 <div id="modal_area" class="hidden"></div>
 <% html_title t(:show_person, name: @person.name) %>